### ISSUE TITLE
Unable to use codeql-cpp-queries from the CLI

### ISSUE THREAD

**Issue by prodingerd** [GitHubSecurityLab/CodeQL-Community-Packs#25]
I am trying to analyze a database using the `codeql-cpp-queries` pack; however, I get the error below.

```bash
codeql database analyze db/ \
  --download githubsecuritylab/codeql-cpp-queries \
  --format=sarif-latest --output=results.sarif
{                                                    
  "packs" : [                                        
    {                                                
      "name" : "githubsecuritylab/codeql-cpp-queries",
      "version" : "0.0.2",
      "library" : false,
      "result" : "INSTALLED"
    }
  ],
  "packDir" : "/home/user/.codeql/packages"
}
Running queries.
A fatal error occurred: Compiled CodeQL packs cannot reference another pack from one of its query suites. 'githubsecuritylab/codeql-cpp-queries@0.0.2' references 'github-queries-ruby'.
```

I have found this [issue](https://github.com/github/codeql/issues/8412) already, but I think it is only somewhat related, as we have two different packs here, i.e., `codeql-cpp-queries` and `github-queries-ruby`. How can I fix this error so that I can run the GitHubSecurityLab packs? 

**CodeQL Version**

The CodeQL CLI resides at `/opt/codeql/codeql`, and the [CodeQL repository](https://github.com/github/codeql) was downloaded to `/opt/codeql/codeql-repo` as per the advanced setup guide.

```text
codeql --version
CodeQL command-line toolchain release 2.15.1.
Copyright (C) 2019-2023 GitHub, Inc.
Unpacked in: /opt/codeql/codeql
```

**Comment by GeekMasher** [comment]
@prodingerd You are absolutely right and this PR should help #26
