### ISSUE TITLE
How to use the lib qlpack folder ?

### ISSUE THREAD

**Issue by hugo-syn** [GitHubSecurityLab/CodeQL-Community-Packs#91]
Hi, thanks for all these great queries, I have a question, how to use the githubsecuritylab/codeql-java-libs pack ? Is it enough to import it or do I need to reference for example FieldReadTaintStep as an additional taint step in my own queries ?

Thanks 🙏

**Comment by Kwstubbs** [comment]
Hi Hugo, if you are using a query that uses TaintTracking class then it should be enough to just import ResearchMode.qll to get FieldReadTaintStep automatically added to the additional steps.
